### ISSUE TITLE
there're errors because of whatsappweb.js and puppeteer updates 

### ISSUE THREAD

**Issue by Bala7a198** [subinps/TG-WhatsApp#2]
the bot crached since the latest updates . I hope you'll fix it soon

**Comment by subinps** [comment]
> the bot crached since the latest updates . I hope you'll fix it soon

It would be helpful if you could provide error logs.

**Comment by marcaureln** [comment]
Run into some issue when trying to generate the session.secure file, right after scanning the QRcode, this is what I got and no file was generated:

```
/home/alex/projects/TG-WhatsApp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'isMDBackend')
    at __puppeteer_evaluation_script__:13:68
    at ExecutionContext._evaluateInternal (/home/alex/projects/TG-WhatsApp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/alex/projects/TG-WhatsApp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.initialize (/home/alex/projects/TG-WhatsApp/node_modules/whatsapp-web.js/src/Client.js:221:9)
```
